pipeline:
  name: test-cruise-control
  identifier: testcruisecontrol
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: cruise-control
        build: <+input>
  stages:
    - stage:
        name: test-multi-arch
        identifier: testmultiarch
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: run unit tests
                  identifier: run_unit_tests
                  spec:
                    shell: Sh
                    command: docker run --rm --privileged tonistiigi/binfmt:latest --install all
              - step:
                  type: Run
                  name: run unit tests 2
                  identifier: run_unit_tests_2
                  spec:
                    shell: Sh
                    command: |2-
                               docker run --rm \
                                 --platform << parameters.platform >> \
                                 --name qemu-cross-<< parameters.platform >> \
                                 --mount type=bind,source=${PWD},target=/github_workspace \
                                 --workdir /github_workspace \
                                 << parameters.platform >>/eclipse-temurin:11-jdk-focal uname -a; ./gradlew --no-daemon -PmaxParallelForks=1 build
          sharedPaths:
            - /workspace
        variables:
          - name: _JAVA_OPTIONS
            type: String
            description: ""
            value: "-Xms512m -Xmx1g"
          - name: DOCKER_CLI_EXPERIMENTAL
            type: String
            description: ""
            value: enabled
