pipeline:
  name: test-cruise-control
  identifier: testcruisecontrol
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: cruise-control
        build: <+input>
  stages:
    - stage:
        name: test-multi-arch
        identifier: testmultiarch
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: run unit tests
                  identifier: run_unit_tests
                  spec:
                    shell: Sh
                    command: docker run --rm --privileged tonistiigi/binfmt:latest --install all
